### ISSUE TITLE
Ability to specify required or preferred Service Manager

### ISSUE THREAD

**Issue by yoiang** [jvehent/service-go#8]
Hey @jvehent !
I'm excited to use __service-go__. It'd be great to be able to specify which service manager to use rather than reading which is available from `/proc/1/cmdline`. An example usage: we have machines that have both __init__ and __systemd__ installed. While __init__ is what's available via `/proc/1/cmdline`, and I am not familiar enough to know why, __systemd__ is what we use to manage our services.

To still encourage __service-go__'s flexibility this specification would probably be optional and done per platform. It would also have to fall back automatically when the specified manager isn't available.

Haha, I hope that's not a lot! If I have a chance I'll take a crack at it and give a pull request!

**Comment by jvehent** [comment]
You should try using https://github.com/kardianos/service instead of this library. Mine is a fork of kardianos' that I made a couple years back to implement specific features for MIG, but I'm not really maintaining it anymore.

**Comment by yoiang** [comment]
Ah great, thanks for the lead!
